### ISSUE TITLE
Error in Configuration Builder when passing manual configuration with relative path

### ISSUE THREAD

**Issue by marvin-schl** [marvin-schl/cs-fmu-mapper#11]
## Steps to reproduce

Call cs-fmu-mapper from with relative path to full configuration file

```python
python main.py -c path/to/full/config.yaml
````

## Error

It seems like something with path construction is broken. 

```
Traceback (most recent call last):
  File "Some\\Absolute\\Path\envs\cs-fmu-mapper\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "Some\\Absolute\\Path\anaconda3\envs\cs-fmu-mapper\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "Some\\Absolute\\Path\cs-fmu-mapper\cs_fmu_mapper\main.py", line 51, in <module>
    config = Config(config_file_path=args.config_path).get_config()
  File "Some\\Absolute\\Path\cs-fmu-mapper\cs_fmu_mapper\config.py", line 31, in __init__
    self._settings_config = self._load_partial_settings(
  File "Some\\Absolute\\Path\cs-fmu-mapper\cs_fmu_mapper\config.py", line 342, in _load_partial_settings
    with open(settings_path, "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'Some\\Absolute\\Path\\cs-fmu-mapper\\example\\configs\\..\\Modelica\\Config\\win64\\friwa_simple_with_plc.yaml'
```
Following Command was executed:

```python
python main.py -c ..\Modelica\Config\win64\friwa_simple_with_plc.yaml

````

**Comment by FrederikBornemann** [comment]
The issue is that the `ConfigurationBuilder` takes two arguments: `config_file_path` and `config_dir`. The path to the configuration (modular or full) is then constructed as `{config_dir}/{config_file_path}`. The `main.py` script accepts the `-c` argument, which sets the value of `config_file_path`. As a result, the path becomes something like `Some\\Absolute\\Path\\cs-fmu-mapper\\example\\configs\\..\\Modelica\\Config\\win64\\friwa_simple_with_plc.yaml`.

This approach is typically used because modular configurations require access to specific module directories (e.g., `/model/`, `/connection/`). However, if a configuration file is located outside the `config_dir` hierarchy, it cannot currently be accessed without modifying `config_dir`. Unfortunately, this adjustment cannot be made via the arguments passed to `main.py`.

This requires a fix.
